// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorColorPreview
{
    internal sealed partial class Vsix
    {
        public const string Id = "EditorColorPreview.0ad29806-3e85-4a3d-8ed8-08934c66375a";
        public const string Name = "Color Preview";
        public const string Description = @"Shows a color preview in front of all named colors, hex, rgb and hsl values in CSS, JavaScript, and C# files. Supports Unity, Godot, MonoGame, FNA, and Raylib_cs color constructors.";
        public const string Language = "en-US";
        public const string Version = "1.1.0";
        public const string Author = "Alexandre Castro";
        public const string Tags = "color, css, hsl, rgb, hex, csharp, unity, godot, monogame, fna, raylib";
        public const bool IsPreview = false;
    }
}